git clone https://github.com/gulpjs/findup-sync.git
git clone https://github.com/gulpjs/gulp.git
git clone https://github.com/gulpjs/glob-stream.git
git clone https://github.com/gulpjs/gulp-util.git
git clone https://github.com/gulpjs/artwork.git
git clone https://github.com/gulpjs/glob-watcher.git
git clone https://github.com/gulpjs/vinyl.git
git clone https://github.com/gulpjs/vinyl-fs.git
git clone https://github.com/gulpjs/gulpjs.github.io.git
git clone https://github.com/gulpjs/plugins.git
git clone https://github.com/gulpjs/acceptance.git
git clone https://github.com/gulpjs/ordered-read-streams.git
git clone https://github.com/gulpjs/hacker.git
git clone https://github.com/gulpjs/async-done.git
git clone https://github.com/gulpjs/replace-ext.git
git clone https://github.com/gulpjs/async-settle.git
git clone https://github.com/gulpjs/bach.git
git clone https://github.com/gulpjs/rechoir.git
git clone https://github.com/gulpjs/interpret.git
git clone https://github.com/gulpjs/registry.git
git clone https://github.com/gulpjs/empty-dir.git
git clone https://github.com/gulpjs/v8flags.git
git clone https://github.com/gulpjs/now-and-later.git
git clone https://github.com/gulpjs/undertaker.git
git clone https://github.com/gulpjs/undertaker-registry.git
git clone https://github.com/gulpjs/flagged-respawn.git
git clone https://github.com/gulpjs/undertaker-common-tasks.git
git clone https://github.com/gulpjs/sparkles.git
git clone https://github.com/gulpjs/gulp-cli.git
git clone https://github.com/gulpjs/glogg.git
git clone https://github.com/gulpjs/semver-greatest-satisfied-range.git
git clone https://github.com/gulpjs/glob-parent.git
git clone https://github.com/gulpjs/undertaker-task-metadata.git
git clone https://github.com/gulpjs/async-once.git
git clone https://github.com/gulpjs/default-resolution.git
git clone https://github.com/gulpjs/last-run.git
git clone https://github.com/gulpjs/plugin-error.git
git clone https://github.com/gulpjs/undertaker-forward-reference.git
git clone https://github.com/gulpjs/gulplog.git
git clone https://github.com/gulpjs/mute-stdout.git
git clone https://github.com/gulpjs/fancy-log.git
git clone https://github.com/gulpjs/has-gulplog.git
git clone https://github.com/gulpjs/eslint-config-gulp.git
git clone https://github.com/gulpjs/jscs-preset-gulp.git
git clone https://github.com/gulpjs/better-stats.git
git clone https://github.com/gulpjs/value-or-function.git
git clone https://github.com/gulpjs/fined.git
git clone https://github.com/gulpjs/conventional-changelog-gulp.git
git clone https://github.com/gulpjs/vinyl-prepare.git
git clone https://github.com/gulpjs/vinyl-sourcemap.git
git clone https://github.com/gulpjs/copy-props.git
git clone https://github.com/gulpjs/clone-buffer.git
git clone https://github.com/gulpjs/each-props.git
git clone https://github.com/gulpjs/path-dirname.git
git clone https://github.com/gulpjs/lead.git
git clone https://github.com/gulpjs/to-through.git
git clone https://github.com/gulpjs/fs-mkdirp-stream.git
git clone https://github.com/gulpjs/resolve-options.git
git clone https://github.com/gulpjs/remove-bom-stream.git
git clone https://github.com/gulpjs/blog.git
git clone https://github.com/gulpjs/replace-homedir.git
git clone https://github.com/gulpjs/theming-log.git
git clone https://github.com/gulpjs/parse-node-version.git
git clone https://github.com/gulpjs/evented-require.git
git clone https://github.com/gulpjs/emit-mapper.git
git clone https://github.com/gulpjs/vinyl-contents.git
git clone https://github.com/gulpjs/.github.git
git clone https://github.com/gulpjs/.boilerplate.git
git clone https://github.com/gulpjs/update-template.git
git clone https://github.com/gulpjs/prettier_action.git
git clone https://github.com/sindresorhus/gulp-imagemin.git
